# The fully qualified name of your lexer that implements the interface JmmLexer
LexerClass=pt.up.fe.comp2026.lexer.JmmLexerImpl
# The fully qualified name of your class that implements the interface JmmParser
ParserClass=pt.up.fe.comp2026.parser.JmmParserImpl
# The fully qualified name of your class that implements the interface JmmAnalysis
AnalysisClass=pt.up.fe.comp2026.analysis.JmmAnalysisImpl
# The fully qualified name of your class that implements the interface JmmOptimization
OptimizationClass=pt.up.fe.comp2026.optimization.JmmOptimizationImpl
# The fully qualified name of your class that implements the interface JasminBackend
BackendClass=pt.up.fe.comp2026.backend.JasminBackendImpl
